import csv
import json
import subprocess
from pathlib import Path
from datetime import datetime, timezone

BASE = Path(__file__).resolve().parents[1]

CSV_PATH = BASE / "data" / "replay_price_updates.csv"
PORTFOLIO_SNAPSHOT = BASE / "data" / "portfolio_snapshot.json"
MANUAL_ACTIONS = BASE / "data" / "manual_actions_journal.jsonl"
AGENT_SUGGESTIONS = BASE / "data" / "agent_suggestions_journal.jsonl"
THESIS_HEALTH = BASE / "data" / "thesis_health_journal.jsonl"


def now_utc():
    return datetime.now(timezone.utc).isoformat()


def load_json(path, default):
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return default


def save_json(path, data):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2, ensure_ascii=False), encoding="utf-8")


def append_jsonl(path, row):
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("a", encoding="utf-8") as f:
        f.write(json.dumps(row, ensure_ascii=False) + "\n")


def safe_float(value):
    try:
        if value in [None, ""]:
            return None
        return float(value)
    except Exception:
        return None


def as_bool(value):
    return str(value or "").strip().lower() in ["1", "true", "yes", "y"]


def ensure_template():
    if CSV_PATH.exists():
        return

    CSV_PATH.parent.mkdir(parents=True, exist_ok=True)

    rows = [
        {
            "ticker": "AAPL",
            "current_price": "",
            "reference_price": "",
            "log_manual": "true",
            "log_agent": "true",
            "log_thesis": "true"
        }
    ]

    with CSV_PATH.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(
            f,
            fieldnames=[
                "ticker",
                "current_price",
                "reference_price",
                "log_manual",
                "log_agent",
                "log_thesis"
            ]
        )
        writer.writeheader()
        writer.writerows(rows)


def update_portfolio(ticker, current_price):
    portfolio = load_json(PORTFOLIO_SNAPSHOT, {})
    portfolio.setdefault("positions", {})

    old = portfolio["positions"].get(ticker, {})

    portfolio["positions"][ticker] = {
        "ticker": ticker,
        "quantity": old.get("quantity", 0),
        "average_cost": old.get("average_cost", 0),
        "current_price": current_price,
        "market_value": old.get("market_value", 0),
        "unrealized_pnl": old.get("unrealized_pnl", 0),
        "notes": "Batch replay current price update",
        "updated_at": now_utc(),
        "advisory_only": True
    }

    portfolio["updated_at"] = now_utc()
    portfolio["source"] = "decision_replay_batch_prices"
    portfolio["advisory_only"] = True

    save_json(PORTFOLIO_SNAPSHOT, portfolio)


def log_manual(ticker, reference_price):
    row = {
        "timestamp": now_utc(),
        "ticker": ticker,
        "action_type": "watch",
        "price": reference_price,
        "quantity": 0,
        "reason": "Batch replay-ready watch record with non-zero reference price",
        "notes": "Generated by decision_replay_batch_prices.py",
        "tags": ["batch", "replay"],
        "source": "decision_replay_batch_prices",
        "advisory_only": True
    }
    append_jsonl(MANUAL_ACTIONS, row)


def log_agent(ticker, reference_price):
    row = {
        "timestamp": now_utc(),
        "ticker": ticker,
        "suggestion_type": "wait_for_confirmation",
        "reference_price": reference_price,
        "confidence": "medium",
        "agent": "decision_replay_batch_prices",
        "model": "manual_input",
        "reason": "Batch replay-ready agent suggestion record",
        "notes": "Generated by decision_replay_batch_prices.py",
        "tags": ["batch", "agent", "replay"],
        "source": "decision_replay_batch_prices",
        "advisory_only": True
    }
    append_jsonl(AGENT_SUGGESTIONS, row)


def log_thesis(ticker):
    row = {
        "timestamp": now_utc(),
        "ticker": ticker,
        "thesis_status": "needs_review",
        "conviction": "medium",
        "supporting_evidence": "Ticker is active in replay workflow.",
        "invalidating_evidence": "Needs confirmation from volume, relative strength, macro, and narrative.",
        "notes": "Generated by decision_replay_batch_prices.py",
        "tags": ["batch", "thesis", "replay"],
        "source": "decision_replay_batch_prices",
        "advisory_only": True
    }
    append_jsonl(THESIS_HEALTH, row)


def run_refresh():
    results = []

    commands = [
        ("decision_data", ["py", "tools\\decision_data_engine.py"]),
        ("decision_replay", ["py", "tools\\decision_replay_engine.py"]),
        ("decision_replay_interpreter", ["py", "tools\\decision_replay_interpreter.py"]),
    ]

    for label, cmd in commands:
        r = subprocess.run(cmd, cwd=BASE, capture_output=True, text=True, timeout=180)
        results.append({
            "label": label,
            "status": "complete" if r.returncode == 0 else "error",
            "returncode": r.returncode,
            "stdout_tail": r.stdout[-500:],
            "stderr_tail": r.stderr[-500:]
        })

    return results


def main():
    ensure_template()

    updated = []
    skipped = []

    with CSV_PATH.open("r", newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)

        for row in reader:
            ticker = str(row.get("ticker", "")).strip().upper()
            current_price = safe_float(row.get("current_price"))
            reference_price = safe_float(row.get("reference_price"))

            if not ticker:
                skipped.append({"row": row, "reason": "missing_ticker"})
                continue

            if current_price is None or current_price <= 0:
                skipped.append({"ticker": ticker, "reason": "missing_or_invalid_current_price"})
                continue

            update_portfolio(ticker, current_price)

            actions = ["portfolio_current_price_updated"]

            if reference_price is not None and reference_price > 0:
                if as_bool(row.get("log_manual")):
                    log_manual(ticker, reference_price)
                    actions.append("manual_logged")

                if as_bool(row.get("log_agent")):
                    log_agent(ticker, reference_price)
                    actions.append("agent_logged")

            if as_bool(row.get("log_thesis")):
                log_thesis(ticker)
                actions.append("thesis_logged")

            updated.append({
                "ticker": ticker,
                "current_price": current_price,
                "reference_price": reference_price,
                "actions": actions
            })

    refresh_results = run_refresh()

    print(json.dumps({
        "status": "complete",
        "csv": str(CSV_PATH),
        "updated": updated,
        "skipped": skipped,
        "refresh_results": refresh_results
    }, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    main()
