import argparse
import json
import subprocess
from pathlib import Path
from datetime import datetime, timezone

BASE = Path(__file__).resolve().parents[1]

REPLAY_PATH = BASE / "features" / "latest_decision_replay.json"
PORTFOLIO_SNAPSHOT = BASE / "data" / "portfolio_snapshot.json"
MANUAL_ACTIONS = BASE / "data" / "manual_actions_journal.jsonl"
AGENT_SUGGESTIONS = BASE / "data" / "agent_suggestions_journal.jsonl"
THESIS_HEALTH = BASE / "data" / "thesis_health_journal.jsonl"


def now_utc():
    return datetime.now(timezone.utc).isoformat()


def load_json(path, default):
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return default


def save_json(path, data):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2, ensure_ascii=False), encoding="utf-8")


def append_jsonl(path, row):
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("a", encoding="utf-8") as f:
        f.write(json.dumps(row, ensure_ascii=False) + "\n")


def run_engine(label, cmd):
    r = subprocess.run(cmd, cwd=BASE, capture_output=True, text=True, timeout=180)
    return {
        "label": label,
        "status": "complete" if r.returncode == 0 else "error",
        "returncode": r.returncode,
        "stdout_tail": r.stdout[-800:],
        "stderr_tail": r.stderr[-800:]
    }


def safe_float(raw):
    try:
        if raw in [None, ""]:
            return None
        return float(raw)
    except Exception:
        return None


def get_missing_tickers():
    replay = load_json(REPLAY_PATH, {})
    tickers = replay.get("tickers_missing_current_price", [])
    if not isinstance(tickers, list):
        return []
    return sorted(set(str(x).upper() for x in tickers if x))


def update_portfolio_price(ticker, current_price):
    portfolio = load_json(PORTFOLIO_SNAPSHOT, {})
    portfolio.setdefault("positions", {})

    old = portfolio["positions"].get(ticker, {})

    portfolio["positions"][ticker] = {
        "ticker": ticker,
        "quantity": old.get("quantity", 0),
        "average_cost": old.get("average_cost", 0),
        "current_price": current_price,
        "market_value": old.get("market_value", 0),
        "unrealized_pnl": old.get("unrealized_pnl", 0),
        "notes": "Auto-updated by replay automation",
        "updated_at": now_utc(),
        "advisory_only": True
    }

    portfolio["updated_at"] = now_utc()
    portfolio["source"] = "decision_replay_autofill"
    portfolio["advisory_only"] = True

    save_json(PORTFOLIO_SNAPSHOT, portfolio)


def log_manual_replay_record(ticker, reference_price):
    row = {
        "timestamp": now_utc(),
        "ticker": ticker,
        "action_type": "watch",
        "price": reference_price,
        "quantity": 0,
        "reason": "Auto replay-ready watch record with non-zero reference price",
        "notes": "Generated by decision_replay_autofill.py",
        "tags": ["automation", "replay"],
        "source": "decision_replay_autofill",
        "advisory_only": True
    }
    append_jsonl(MANUAL_ACTIONS, row)


def log_agent_replay_record(ticker, reference_price):
    row = {
        "timestamp": now_utc(),
        "ticker": ticker,
        "suggestion_type": "wait_for_confirmation",
        "reference_price": reference_price,
        "confidence": "medium",
        "agent": "decision_replay_autofill",
        "model": "manual_input",
        "reason": "Auto replay-ready agent suggestion record",
        "notes": "Generated by decision_replay_autofill.py",
        "tags": ["automation", "agent", "replay"],
        "source": "decision_replay_autofill",
        "advisory_only": True
    }
    append_jsonl(AGENT_SUGGESTIONS, row)


def log_thesis_record(ticker):
    row = {
        "timestamp": now_utc(),
        "ticker": ticker,
        "thesis_status": "needs_review",
        "conviction": "medium",
        "supporting_evidence": "Ticker is active in replay workflow.",
        "invalidating_evidence": "Needs confirmation from volume, relative strength, macro, and narrative.",
        "notes": "Generated by decision_replay_autofill.py",
        "tags": ["automation", "thesis", "replay"],
        "source": "decision_replay_autofill",
        "advisory_only": True
    }
    append_jsonl(THESIS_HEALTH, row)


def refresh_all():
    results = []
    results.append(run_engine("decision_data", ["py", "tools\\decision_data_engine.py"]))
    results.append(run_engine("decision_replay", ["py", "tools\\decision_replay_engine.py"]))
    results.append(run_engine("decision_replay_interpreter", ["py", "tools\\decision_replay_interpreter.py"]))
    return results


def main():
    parser = argparse.ArgumentParser(description="Automate replay readiness using user-entered prices. Advisory only.")
    parser.add_argument("--ticker", default="", help="Ticker to update. If omitted, uses missing tickers from replay.")
    parser.add_argument("--current-price", type=float, default=None)
    parser.add_argument("--reference-price", type=float, default=None)
    parser.add_argument("--log-manual", action="store_true")
    parser.add_argument("--log-agent", action="store_true")
    parser.add_argument("--log-thesis", action="store_true")
    parser.add_argument("--interactive", action="store_true")
    args = parser.parse_args()

    tickers = []
    if args.ticker:
        tickers = [args.ticker.upper()]
    else:
        tickers = get_missing_tickers()

    if not tickers:
        print(json.dumps({
            "status": "nothing_to_update",
            "message": "No missing current-price tickers found. Run decision_replay_engine first if needed."
        }, indent=2))
        return

    updated = []

    for ticker in tickers:
        current_price = args.current_price
        reference_price = args.reference_price

        if args.interactive or current_price is None:
            raw = input(f"Enter current price for {ticker}: ").strip()
            current_price = safe_float(raw)

        if current_price is None or current_price <= 0:
            print(f"Skipping {ticker}: current price must be greater than 0.")
            continue

        if args.interactive and reference_price is None:
            raw = input(f"Enter reference/action price for {ticker} or press Enter to skip replay record: ").strip()
            reference_price = safe_float(raw)

        update_portfolio_price(ticker, current_price)

        actions = ["portfolio_current_price_updated"]

        if reference_price is not None and reference_price > 0:
            if args.log_manual:
                log_manual_replay_record(ticker, reference_price)
                actions.append("manual_replay_record_logged")

            if args.log_agent:
                log_agent_replay_record(ticker, reference_price)
                actions.append("agent_replay_record_logged")

        if args.log_thesis:
            log_thesis_record(ticker)
            actions.append("thesis_record_logged")

        updated.append({
            "ticker": ticker,
            "current_price": current_price,
            "reference_price": reference_price,
            "actions": actions
        })

    refresh_results = refresh_all()

    print(json.dumps({
        "status": "complete",
        "updated": updated,
        "refresh_results": refresh_results
    }, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    main()
